import turtle
from turtle import *
pensize(3)
speed(0)
turtle.screensize(bg='orange')
pencolor('black')
def circle_draw(color, radius, x, y):
    penup()
    fillcolor(color)
    goto(x,y)
    pendown()
    begin_fill()
    circle(radius)
    end_fill()

circle_draw("white", 30, 0,-40)
circle_draw('white', 40, 0, -100)
circle_draw('white', 60, 0, -200)

circle_draw('white', 2, -10, -10)
circle_draw('white', 2, 10, -10)
circle_draw('red', 3, 0, -15)

circle_draw('white', 2, 0, -35)
circle_draw('white', 2, 0, -45)
circle_draw('white', 2, 0, -55)

penup()
goto(-15, -35)
pendown()
pensize(5)
goto(-80, -50)

penup()
goto(15, -35)
pendown()
pensize(5)
goto(80, -50)

penup()
goto(-35,10)
color('black')
pensize(6)
pendown()
goto(35,10)

goto(30, 8)
fillcolor('skyblue')
begin_fill()
left(90)
forward(15)
left(90)
forward(60)
left(90)
forward(15)
end_fill()
hideturtle()
exitonclick()
done()